# Generated by Django 4.1.5 on 2023-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapiapp', '0002_rename_user_userprofile_user_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
