# Generated by Django 4.1.5 on 2023-01-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapiapp', '0003_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Votes',
        ),
    ]
