# Generated by Django 4.1.5 on 2023-01-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapiapp', '0004_remove_vote_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Votes',
        ),
    ]
